### ISSUE TITLE
Title or another fields value of linked record

### ISSUE THREAD

**Issue by SergeyRe** [cj/datocms-plugin-better-title#1]
By default i have only id of linked record on output
Is it possible to retrieve other fields values ?

**Comment by cj** [comment]
@SergeyRe yes, that's what this plugin is for.  Can you tell me what you want to display and about your linked record; then I can help you set it up if you like?

**Comment by SergeyRe** [comment]
![image](https://user-images.githubusercontent.com/38654146/48975998-95dbce00-f08f-11e8-98e0-7cb32db8f13e.png)
![image](https://user-images.githubusercontent.com/38654146/48976011-dfc4b400-f08f-11e8-8715-449fac81aeaa.png)
I made editor setting for "ccc" field as Better Title (aaa,ddd)
aaa -is single text type and ddd -linked type 
Expected value for ccc -value of aaa + value of title of ddd

**Comment by SergeyRe** [comment]
Sorry , i tried ddd:title -but it doesn't work :(

**Comment by cj** [comment]
@SergeyRe did you add the api token? ![](https://cl.ly/78484f30f954/Image%2525202018-11-25%252520at%2525208.58.31%252520AM.png)

**Comment by SergeyRe** [comment]
Yes you are right
i think you have to make this point more highlighted :))
Thank you

**Comment by cj** [comment]
@SergeyRe no problem, glad you got it working 😄 

I'll make a detailed README that highlights these points more, cheers!
